<?php
/** Accessibility Statement. Content supplied from the legacy LT Transfers website. */
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle       = 'Accessibility | ' . SITE_NAME;
$pageDescription = 'Our commitment to WCAG 2.1 AA accessibility, the tools we use, and how to reach us with feedback.';
$canonicalPath   = '/accessibility';
$bodyClass       = 'page-legal page-accessibility';

require SITE_ROOT . '/common-template/header.php';
?>

<main class="legal-main">
  <section class="page-hero legal-hero">
    <div class="breadcrumbs"><a href="<?= base_url('index.php') ?>">Home</a><span aria-hidden="true">/</span><span>Accessibility</span></div>
    <div class="legal-hero-grid">
      <div><p class="eyebrow">Our commitment</p><h1>Accessibility</h1><p class="lede">How <?= h(SITE_NAME) ?> works to make this website usable by the broadest possible audience, regardless of ability.</p></div>
      <aside><span>Last updated</span><strong>October 4, 2023</strong><p>We continually review and improve our accessibility.</p></aside>
    </div>
  </section>

  <section class="section legal-section">
    <div class="legal-layout">
      <aside class="legal-sidebar">
        <p class="eyebrow">On this page</p>
        <nav aria-label="Accessibility sections">
          <a href="#compliance-status">Compliance Status</a><a href="#screen-reader-keyboard">Screen-Reader &amp; Keyboard Navigation</a><a href="#disability-profiles">Disability Profiles Supported</a><a href="#ui-adjustments">UI &amp; Readability Adjustments</a><a href="#browser-compatibility">Assistive Technology &amp; Browser Compatibility</a><a href="#feedback">Notes, Comments &amp; Feedback</a><a href="#contact-information">Contact Information</a>
        </nav>
        <div class="legal-help"><strong>Need an accommodation?</strong><a href="<?= base_url('contact') ?>">Contact our team <span aria-hidden="true">&rarr;</span></a></div>
      </aside>

      <article class="legal-content">
        <section id="compliance-status"><span class="legal-section-number">01</span><h2>Compliance Status</h2><p>We firmly believe that the internet should be available and accessible to anyone and are committed to providing a website that is accessible to the broadest possible audience, regardless of ability.</p><p>To fulfill this, we aim to adhere as strictly as possible to the World Wide Web Consortium&rsquo;s (W3C) Web Content Accessibility Guidelines 2.1 (WCAG 2.1) at the AA level. These guidelines explain how to make web content accessible to people with a wide array of disabilities. Complying with those guidelines helps us ensure that the website is accessible to blind people, people with motor impairments, visual impairment, cognitive disabilities, and more.</p><p>This website utilizes various technologies that are meant to make it as accessible as possible at all times. We utilize an accessibility interface that allows persons with specific disabilities to adjust the website&rsquo;s UI (user interface) and design it to their personal needs.</p><p>Additionally, the website utilizes an AI-based application that runs in the background and optimizes its accessibility level constantly. This application remediates the website&rsquo;s HTML, adapts its functionality and behavior for screen-readers used by blind users, and for keyboard functions used by individuals with motor impairments.</p><p>If you wish to contact the website&rsquo;s owner, please use the following email: <a href="mailto:<?= h(COMPANY_EMAIL) ?>"><?= h(COMPANY_EMAIL) ?></a>.</p></section>

        <section id="screen-reader-keyboard"><span class="legal-section-number">02</span><h2>Screen-Reader and Keyboard Navigation</h2><p>Our website implements the ARIA (Accessible Rich Internet Applications) attributes technique, alongside various behavioral changes, to ensure blind users visiting with screen-readers can read, comprehend, and enjoy the website&rsquo;s functions. As soon as a user with a screen-reader enters the site, they immediately receive a prompt to enter the Screen-Reader Profile so they can browse and operate the site effectively. Here&rsquo;s how our website covers some of the most important screen-reader requirements:</p><ol><li><strong>Screen-reader optimization.</strong> We run a process that learns the website&rsquo;s components from top to bottom, to ensure ongoing compliance even when updating the website. In this process, we provide screen-readers with meaningful data using the ARIA set of attributes &mdash; for example, accurate form labels; descriptions for actionable icons (social media icons, search icons, cart icons, etc.); validation guidance for form inputs; and element roles such as buttons, menus, and modal dialogues (popups). Additionally, the background process scans all of the website&rsquo;s images and provides an accurate and meaningful image-object-recognition-based description as an ALT (alternate text) tag for images that are not described. It will also extract text embedded within images using OCR (optical character recognition) technology. To turn on screen-reader adjustments at any time, users need only press the Alt+1 keyboard combination. Screen-reader users also get automatic announcements to turn Screen-reader mode on as soon as they enter the website. These adjustments are compatible with popular screen readers such as JAWS, NVDA, VoiceOver, and TalkBack.</li><li><strong>Keyboard navigation optimization.</strong> The background process also adjusts the website&rsquo;s HTML and adds various behaviors using JavaScript code to make the website operable by the keyboard. This includes the ability to navigate the website using the Tab and Shift+Tab keys, operate dropdowns with the arrow keys, close them with Esc, trigger buttons and links using the Enter key, navigate between radio and checkbox elements using the arrow keys, and fill them in with the Spacebar or Enter key. Additionally, keyboard users will find content-skip menus available at any time by pressing Alt+2, or as the first element of the site while navigating with the keyboard. The background process also handles triggered popups by moving the keyboard focus toward them as soon as they appear, not allowing the focus to drift outside. Users can also use shortcuts such as &ldquo;M&rdquo; (menus), &ldquo;H&rdquo; (headings), &ldquo;F&rdquo; (forms), &ldquo;B&rdquo; (buttons), and &ldquo;G&rdquo; (graphics) to jump to specific elements.</li></ol></section>

        <section id="disability-profiles"><span class="legal-section-number">03</span><h2>Disability Profiles Supported on Our Website</h2><ul><li><strong>Epilepsy Safe Profile:</strong> this profile enables people with epilepsy to safely use the website by eliminating the risk of seizures resulting from flashing or blinking animations and risky color combinations.</li><li><strong>Vision Impaired Profile:</strong> this profile adjusts the website so that it is accessible to the majority of visual impairments such as degrading eyesight, tunnel vision, cataracts, glaucoma, and others.</li><li><strong>Cognitive Disability Profile:</strong> this profile provides various assistive features to help users with cognitive disabilities such as autism, dyslexia, and CVA, among others, to focus on essential elements more easily.</li><li><strong>ADHD Friendly Profile:</strong> this profile significantly reduces distractions and noise to help people with ADHD and neurodevelopmental disorders browse, read, and focus on essential elements more easily.</li><li><strong>Blind Users Profile (Screen-Readers):</strong> this profile adjusts the website to be compatible with screen-readers such as JAWS, NVDA, VoiceOver, and TalkBack. A screen-reader is installed on the blind user&rsquo;s computer, and this site is compatible with it.</li><li><strong>Keyboard Navigation Profile (Motor-Impaired):</strong> this profile enables motor-impaired persons to operate the website using the keyboard Tab, Shift+Tab, and Enter keys. Users can also use shortcuts such as &ldquo;M&rdquo; (menus), &ldquo;H&rdquo; (headings), &ldquo;F&rdquo; (forms), &ldquo;B&rdquo; (buttons), and &ldquo;G&rdquo; (graphics) to jump to specific elements.</li></ul></section>

        <section id="ui-adjustments"><span class="legal-section-number">04</span><h2>Additional UI, Design, and Readability Adjustments</h2><ol><li><strong>Font adjustments:</strong> users can increase and decrease its size, change its family (type), and adjust the spacing, alignment, line height, and more.</li><li><strong>Color adjustments:</strong> users can select various color contrast profiles such as light, dark, inverted, and monochrome. Additionally, users can swap color schemes of titles, texts, and backgrounds with over seven different coloring options.</li><li><strong>Animations:</strong> epileptic users can stop all running animations with the click of a button. Animations controlled by the interface include videos, GIFs, and CSS flashing transitions.</li><li><strong>Content highlighting:</strong> users can choose to emphasize essential elements such as links and titles. They can also choose to highlight focused or hovered elements only.</li><li><strong>Audio muting:</strong> users with hearing devices may experience headaches or other issues due to automatic audio playing. This option lets users mute the entire website instantly.</li><li><strong>Cognitive disorders:</strong> we utilize a search engine linked to Wikipedia and Wiktionary, allowing people with cognitive disorders to decipher the meanings of phrases, initials, slang, and others.</li><li><strong>Additional functions:</strong> we allow users to change cursor color and size, use a printing mode, enable a virtual keyboard, and access many other functions.</li></ol></section>

        <section id="browser-compatibility"><span class="legal-section-number">05</span><h2>Assistive Technology and Browser Compatibility</h2><p>We aim to support as many browsers and assistive technologies as possible, so our users can choose the tools that fit them best, with as few limitations as possible. We have worked hard to support all major systems that comprise over 95% of the user market share, including Google Chrome, Mozilla Firefox, Apple Safari, Opera, and Microsoft Edge, as well as JAWS and NVDA (screen readers), for both Windows and Mac users.</p></section>

        <section id="feedback"><span class="legal-section-number">06</span><h2>Notes, Comments, and Feedback</h2><p>Despite our very best efforts to allow anybody to adjust the website to their needs, there may still be pages or sections that are not fully accessible, are in the process of becoming accessible, or are lacking an adequate technological solution to make them accessible. Still, we are continually improving our accessibility, adding, updating, and improving its options and features, and developing and adopting new technologies. All this is meant to reach the optimal level of accessibility, following technological advancements. If you wish to contact the website&rsquo;s owner, please use the following email: <a href="mailto:<?= h(COMPANY_EMAIL) ?>"><?= h(COMPANY_EMAIL) ?></a>.</p></section>

        <section id="contact-information"><span class="legal-section-number">07</span><h2>Contact Information</h2><p>We welcome your comments or questions about accessibility on our website. You may <a href="<?= base_url('contact') ?>">contact us</a> through the contact information available on our website.</p><div class="legal-contact-card"><div><span>Telephone</span><a href="tel:+<?= h(COMPANY_PHONE_TEL) ?>"><?= h(COMPANY_PHONE) ?></a></div><div><span>Fax</span><span><?= h(COMPANY_FAX) ?></span></div><div><span>Email</span><a href="mailto:<?= h(COMPANY_EMAIL) ?>"><?= h(COMPANY_EMAIL) ?></a></div><div><span>Mailing address</span><p><?= h(COMPANY_ADDRESS_LINE1) ?><br><?= h(COMPANY_ADDRESS_LINE2) ?></p></div></div></section>
      </article>
    </div>
  </section>
</main>

<?php require SITE_ROOT . '/common-template/footer.php'; ?>
