<?php
require_once __DIR__ . '/includes/bootstrap.php';
$pageTitle = 'How to Transfer a Timeshare Deed | ' . SITE_NAME;
$pageDescription = 'Learn how a timeshare deed transfer works, from pricing and document submission through recording and resort notification.';
$canonicalPath = '/how-it-works-timeshare-deed-transfer';
$bodyClass = 'page-how-it-works';
require SITE_ROOT . '/common-template/header.php';
?>
<main class="process-main">
  <section class="page-hero process-hero">
    <div class="process-hero-grid">
      <div><div class="breadcrumbs"><a href="<?= base_url('index.php') ?>">Home</a><span aria-hidden="true">/</span><span>How It Works</span></div><p class="eyebrow">A clear path from start to finish</p><h1>How to transfer a timeshare deed</h1><p class="lede">We make timeshare deed transfers easier to understand by organizing the documents, recording steps, and resort notification into one guided process.</p><div class="process-hero-actions"><a class="button primary" href="#transfer-steps">See the five steps</a><a class="process-text-link" href="<?= base_url('document-preparation') ?>">Submit your documents <span aria-hidden="true">&rarr;</span></a></div></div>
      <aside class="process-hero-summary"><span>Typical starting range</span><strong>$275&ndash;$450</strong><p>Plus applicable postage, recording fees, and any resort-controlled transfer fee.</p><div><small>Document search</small><b>$25 when needed</b></div></aside>
    </div>
  </section>
  <section class="process-fact-strip" aria-label="Transfer process highlights"><article><span>01</span><strong>Submit online</strong><small>Upload your current deed</small></article><article><span>02</span><strong>Review by email</strong><small>Documents sent for approval</small></article><article><span>03</span><strong>Recording coordinated</strong><small>Typically 1&ndash;6 weeks</small></article><article><span>04</span><strong>Resort notified</strong><small>After the deed returns</small></article></section>
  <section class="section process-intro-section"><div class="process-intro-grid"><div><p class="eyebrow">What to expect</p><h2>A guided transfer process, one step at a time</h2></div><p>Every transfer has different state, county, and resort requirements. These steps show the standard journey and where your specific details may affect cost or timing.</p></div></section>
  <section class="section section-soft process-steps-section" id="transfer-steps"><div class="process-timeline">
    <article><div class="process-step-marker"><span>01</span></div><div class="process-step-card"><p class="eyebrow">Understand the cost</p><h2>Start with a specific quote</h2><p>Document preparation fees vary by state and the requirements for each document. Most initial document preparation fees average between <strong>$275 and $450</strong>, plus postage and recording fees.</p><p>If your resort charges a transfer fee, it is separate from our fees. We forward those funds to the resort when we notify them of the ownership change.</p><div class="process-note"><strong>International ownership?</strong><span>We can also assist with transfers in the U.S. Virgin Islands, Aruba, and Mexico. Contact us for a custom quote.</span></div><a href="<?= base_url('fees') ?>">Review pricing details <span aria-hidden="true">&rarr;</span></a></div></article>
    <article><div class="process-step-marker"><span>02</span></div><div class="process-step-card"><p class="eyebrow">Send what you have</p><h2>Complete the online preparation form</h2><p>Fill out our online document preparation form and upload a copy of your current deed. You may also send the information by fax, email, or hard copy. We will email you to confirm receipt.</p><p>If you do not have a copy of your recorded deed, we can conduct a deed search for a <strong>$25 research fee</strong>.</p><a class="button primary" href="<?= base_url('document-preparation') ?>">Submit document information</a></div></article>
    <article><div class="process-step-marker"><span>03</span></div><div class="process-step-card"><p class="eyebrow">Preparation and review</p><h2>We prepare the new transfer documents</h2><p>After receiving the information needed, we prepare the documents required to transfer your timeshare. When they are ready, we email them to you for review together with the final invoice.</p></div></article>
    <article><div class="process-step-marker"><span>04</span></div><div class="process-step-card"><p class="eyebrow">Execution and recording</p><h2>Signed documents go to the Clerk&rsquo;s office</h2><p>Once we receive the properly executed documents, we send them to the appropriate Clerk&rsquo;s office for recording.</p><div class="process-time-card"><span>Typical county recording time</span><strong>1&ndash;6 weeks</strong><small>Timing varies by county.</small></div></div></article>
    <article><div class="process-step-marker"><span>05</span></div><div class="process-step-card"><p class="eyebrow">Completion</p><h2>We notify you and the resort</h2><p>When the recorded deed returns to our office, we notify you by email. We then send a copy of the recorded deed and a cover letter to your resort for the ownership transfer.</p><p>That&rsquo;s it&mdash;your deed transfer documentation and resort notification are complete.</p><div class="process-complete-actions"><a class="button primary" href="<?= base_url('booking') ?>">Start your transfer</a><a class="button secondary" href="<?= base_url('testimonials') ?>">Read owner reviews</a></div></div></article>
  </div></section>
  <section class="section process-proof-section"><div class="process-proof-grid"><div><p class="eyebrow">Owner experience</p><blockquote>&ldquo;LT Transfers made the whole timeshare transfer process so smooth and stress-free. They were clear, responsive, and very quick with every step of the way.&rdquo;</blockquote><cite>Shirley</cite></div><aside><span>Still unsure about a step?</span><h2>Tell us what you own. We&rsquo;ll explain what comes next.</h2><a class="button primary" href="<?= base_url('contact') ?>">Ask our team</a></aside></div></section>
  <section class="final-cta"><div><p class="eyebrow">Ready to begin?</p><h2>Start with the information you have. We will help organize the rest.</h2></div><div class="cta-row"><a class="button primary light" href="<?= base_url('document-preparation') ?>">Submit Your Documents</a><a class="button secondary light" href="tel:+<?= h(COMPANY_PHONE_TEL) ?>">Call <?= h(COMPANY_PHONE) ?></a></div></section>
</main>
<?php require SITE_ROOT . '/common-template/footer.php'; ?>
