<?php
/** Privacy Policy. Content supplied from the legacy LT Transfers website. */
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle       = 'Privacy Policy | ' . SITE_NAME;
$pageDescription = 'How LT Transfers collects, uses, shares, and protects your personal data.';
$canonicalPath   = '/privacy-policy';
$bodyClass       = 'page-legal page-privacy';

require SITE_ROOT . '/common-template/header.php';
?>

<main class="legal-main">
  <section class="page-hero legal-hero">
    <div class="breadcrumbs"><a href="<?= base_url('index.php') ?>">Home</a><span aria-hidden="true">/</span><span>Privacy Policy</span></div>
    <div class="legal-hero-grid">
      <div><p class="eyebrow">Your privacy</p><h1>Privacy Policy</h1><p class="lede">How <?= h(SITE_NAME) ?> collects, uses, shares, and protects your personal data when you use this website.</p></div>
      <aside><span>Last updated</span><strong>December 1, 2020</strong><p>Please read this policy carefully before using this website.</p></aside>
    </div>
  </section>

  <section class="section legal-section">
    <div class="legal-layout">
      <aside class="legal-sidebar">
        <p class="eyebrow">On this page</p>
        <nav aria-label="Privacy Policy sections">
          <a href="#introduction">Introduction</a><a href="#purposes-of-processing">Purposes of Processing</a><a href="#collecting-your-data">Collecting Your Data</a><a href="#cookies">Cookies</a><a href="#advertising">Advertising</a><a href="#using-your-data">Using Your Data</a><a href="#sharing-your-data">Sharing Your Data</a><a href="#user-generated-content">User Generated Content</a><a href="#international-transfer">International Data Transfer</a><a href="#security">Security</a><a href="#retention">Retention</a><a href="#children">Our Policy on Children</a><a href="#your-rights">Your Rights</a><a href="#complaints">Complaints</a><a href="#contact-information">Contact Information</a>
        </nav>
        <div class="legal-help"><strong>Questions about your data?</strong><a href="<?= base_url('contact') ?>">Contact our team <span aria-hidden="true">&rarr;</span></a></div>
      </aside>

      <article class="legal-content">
        <section id="introduction"><span class="legal-section-number">01</span><h2>Introduction</h2><p>This privacy policy (&ldquo;<strong>Policy</strong>&rdquo;) describes how <?= h(SITE_NAME) ?> (&ldquo;<strong>Company,</strong>&rdquo; &ldquo;<strong>we,</strong>&rdquo; and &ldquo;<strong>our</strong>&rdquo;) processes, collects, uses, and shares personal data when using this website, <?= h(SITE_URL) ?> (the &ldquo;<strong>Website</strong>&rdquo;). Please read the following information carefully to understand our practices regarding your personal data and how we will process it.</p></section>

        <section id="purposes-of-processing"><span class="legal-section-number">02</span><h2>Purposes of Processing</h2><p><strong>What is personal data?</strong> We collect information about you in a range of forms, including personal data. As used in this Policy, &ldquo;personal data&rdquo; is any information which, either alone or in combination with other information we process about you, identifies you as an individual, including, for example, your name, postal address, email address, and telephone number.</p><p><strong>Why do we need your personal data?</strong> We will only process your personal data in accordance with applicable data protection and privacy laws. We need certain personal data in order to provide you with access to the Website. If you registered with us, you will have been asked to agree to provide this information in order to access our services, purchase our products, or view our content. This consent provides us with the legal basis we require under applicable law to process your data. You maintain the right to withdraw such consent at any time. If you do not agree to our use of your personal data in line with this Policy, please do not use our Website.</p></section>

        <section id="collecting-your-data"><span class="legal-section-number">03</span><h2>Collecting Your Personal Data</h2><p>We collect information about you in the following ways.</p><p><strong>Information You Give Us.</strong> This includes:</p><ul><li>the personal data you provide when you register to use our Website, including your name, postal address, email address, telephone number, username, password, and demographic information (such as your gender);</li><li>the personal data that may be contained in any video, comment, or other submission you upload or post to the Website;</li><li>the personal data you provide in connection with our rewards program and other promotions we run on the Website;</li><li>the personal data you provide when you report a problem with our Website or when we provide you with customer support;</li><li>the personal data you provide when you make a purchase through our Website; and</li><li>the personal data you provide when you correspond with us by phone, email, or otherwise.</li></ul><p><strong>Information from Social Networking Websites.</strong> Our Website includes interfaces that allow you to connect with social networking sites (each an &ldquo;SNS&rdquo;). If you connect to an SNS through our Website, you authorize us to access, use, and store the information that you agreed the SNS could provide to us based on your settings on that SNS. We will access, use, and store that information in accordance with this Policy. You can revoke our access to the information you provide in this way at any time by amending the appropriate settings from within your account settings on the applicable SNS.</p><p><strong>Information Automatically Collected.</strong> We automatically log information about you and your computer or mobile device when you access our Website. For example, when visiting our Website, we log your device&rsquo;s operating system name and version, manufacturer and model, browser type, browser language, screen resolution, the website you visited before browsing to our Website, pages you viewed, how long you spent on a page, access times, and information about your use of and actions on our Website. We collect this information using cookies.</p><p><strong>Automated Decision Making and Profiling.</strong> We do not use your personal data for the purposes of automated decision-making. However, we may do so in order to fulfill obligations imposed by law, in which case we will inform you of any such processing and provide you with an opportunity to object.</p></section>

        <section id="cookies"><span class="legal-section-number">04</span><h2>Cookies</h2><p><strong>What are cookies?</strong> We may collect information using &ldquo;cookies.&rdquo; Cookies are small data files stored on the hard drive of your computer or mobile device by a website. We may use both session cookies (which expire once you close your web browser) and persistent cookies (which stay on your device until you delete them) to provide you with a more personal and interactive experience on our Website.</p><p>We use two broad categories of cookies: (1) first-party cookies, served directly by us to your device, which are used only by us to recognize your device when it revisits our Website; and (2) third-party cookies, served by service providers on our Website, which can be used by such service providers to recognize your device when it visits other websites.</p><p><strong>Cookies we use.</strong> Our Website uses the following types of cookies for the purposes set out below.</p>
          <div class="legal-table-wrap">
            <table class="legal-table">
              <thead><tr><th>Type of cookie</th><th>Purpose</th></tr></thead>
              <tbody>
                <tr><td><em>Essential Cookies</em></td><td>These cookies are essential to provide you with services available through our Website and to enable you to use some of its features. For example, they allow you to log in to secure areas of our Website and help the content of the pages you request load quickly. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.</td></tr>
                <tr><td><em>Functionality Cookies</em></td><td>These cookies allow our Website to remember choices you make when you use our Website, such as remembering your language preferences, remembering your login details, and remembering changes you make to other parts of our Website which you can customize. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you visit our Website.</td></tr>
                <tr><td><em>Analytics and Performance Cookies</em></td><td><p>These cookies are used to collect information about traffic to our Website and how users use our Website. The information gathered does not identify any individual visitor. It includes the number of visitors to our Website, the websites that referred them to our Website, the pages they visited on our Website, what time of day they visited our Website, whether they have visited our Website before, and other similar information. We use this information to help operate our Website more efficiently, to gather broad demographic information, and to monitor the level of activity on our Website.</p><p>We use Google Analytics for this purpose. Google Analytics uses its own cookies. It is only used to improve how our Website works. You can find out more about Google Analytics cookies at <a href="https://developers.google.com/analytics/resources/concepts/gaConceptsCookies" target="_blank" rel="noopener noreferrer">developers.google.com</a>.</p><p>You can find out more about how Google protects your data at <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">policies.google.com/privacy</a>.</p><p>You can prevent the use of Google Analytics relating to your use of our Website by downloading and installing the <a href="http://tools.google.com/dlpage/gaoptout?hl=en-GB" target="_blank" rel="noopener noreferrer">Google Analytics opt-out browser add-on</a>.</p></td></tr>
                <tr><td><em>Targeted and Advertising Cookies</em></td><td><p>These cookies track your browsing habits to enable us to show advertising which is more likely to be of interest to you. These cookies use information about your browsing history to group you with other users who have similar interests. Based on that information, and with our permission, third-party advertisers can place cookies to enable them to show adverts which we think will be relevant to your interests while you are on third-party websites.</p><p>You can disable cookies which remember your browsing habits and target advertising at you by visiting <a href="http://www.youronlinechoices.com/uk/your-ad-choices" target="_blank" rel="noopener noreferrer">youronlinechoices.com</a>. If you choose to remove targeted or advertising cookies, you will still see adverts, but they may not be relevant to you. Not all companies that serve online behavioral advertising are included in this opt-out, so you may still receive some cookies and tailored adverts from companies that are not listed.</p></td></tr>
                <tr><td><em>Social Media Cookies</em></td><td>These cookies are used when you share information using a social media sharing button or &ldquo;like&rdquo; button on our Website, or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter, or Google+. The social network will record that you have done this.</td></tr>
              </tbody>
            </table>
          </div>
          <p><strong>Disabling cookies.</strong> You can typically remove or reject cookies via your browser settings. In order to do this, follow the instructions provided by your browser (usually located within the &ldquo;settings,&rdquo; &ldquo;help,&rdquo; &ldquo;tools,&rdquo; or &ldquo;edit&rdquo; facility). Many browsers are set to accept cookies until you change your settings.</p>
          <p>If you do not accept our cookies, you may experience some inconvenience in your use of our Website. For example, we may not be able to recognize your device and you may need to log in every time you visit our Website.</p>
        </section>

        <section id="advertising"><span class="legal-section-number">05</span><h2>Advertising</h2><p>We may use other companies to serve third-party advertisements when you visit and use the Website. These companies may collect and use clickstream information, browser type, time and date, and the subject of advertisements clicked or scrolled over during your visits to the Website and other websites in order to provide advertisements about goods and services likely to be of interest to you. These companies typically use tracking technologies to collect this information. Other companies&rsquo; use of their tracking technologies is subject to their own privacy policies.</p></section>

        <section id="using-your-data"><span class="legal-section-number">06</span><h2>Using Your Personal Data</h2><p>We may use your personal data as follows:</p><ul><li>to operate, maintain, and improve our Website, products, and services;</li><li>to manage your account, including to communicate with you regarding your account, if you have an account on our Website;</li><li>to operate and administer our rewards program and other promotions you participate in on our Website;</li><li>to respond to your comments and questions and to provide customer service;</li><li>to send information including technical notices, updates, security alerts, and support and administrative messages;</li><li>with your consent, to send you marketing emails about upcoming promotions and other news, including information about products and services offered by us and our affiliates &mdash; you may opt out of receiving such information at any time, and such marketing emails tell you how to opt out (note that even if you opt out of marketing emails, we may still send you non-marketing emails, such as those about your account or our business dealings with you);</li><li>to process payments you make via our Website;</li><li>as we believe necessary or appropriate to (a) comply with applicable laws; (b) comply with lawful requests and legal process, including requests from public and government authorities; (c) enforce our Policy; and (d) protect our rights, privacy, safety, or property, and/or that of you or others;</li><li>for analysis and study services; and</li><li>as described in the &ldquo;Sharing Your Personal Data&rdquo; section below.</li></ul></section>

        <section id="sharing-your-data"><span class="legal-section-number">07</span><h2>Sharing Your Personal Data</h2><p>We may share your personal data as follows:</p><ul><li><strong>Third Parties Designated by You.</strong> We may share your personal data with third parties where you have provided your consent to do so.</li><li><strong>Our Third-Party Service Providers.</strong> We may share your personal data with our third-party service providers who provide services such as data analysis, payment processing, information technology and related infrastructure provision, customer service, email delivery, auditing, and other similar services.</li><li><strong>Third-Party Sites.</strong> Our Website may contain links to third-party websites and features. This Policy does not cover the privacy practices of such third parties. These third parties have their own privacy policies, and we do not accept any responsibility or liability for their websites, features, or policies. Please read their privacy policies before you submit any data to them.</li></ul></section>

        <section id="user-generated-content"><span class="legal-section-number">08</span><h2>User Generated Content</h2><p>You may share personal data with us when you submit user-generated content to our Website, including via our rewards program, forums, message boards, and other features on our Website. Please note that any information you post or disclose on our Website will become public information and will be available to other users of our Website and to the general public. We urge you to be very careful when deciding to disclose your personal data, or any other information, on our Website. Such personal data and other information will not be private or confidential once it is published on our Website.</p><p>If you provide feedback to us, we may use and disclose such feedback on our Website, provided we do not associate such feedback with your personal data. If you have provided your consent to do so, we may post your first and last name along with your feedback on our Website. We will collect any information contained in such feedback and will treat the personal data in it in accordance with this Policy.</p></section>

        <section id="international-transfer"><span class="legal-section-number">09</span><h2>International Data Transfer</h2><p>Your information, including personal data that we collect from you, may be transferred to, stored at, and processed by us outside the country in which you reside, where data protection and privacy regulations may not offer the same level of protection as in other parts of the world. By accepting this Policy, you agree to this transfer, storing, or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Policy.</p></section>

        <section id="security"><span class="legal-section-number">10</span><h2>Security</h2><p>We seek to use reasonable organizational, technical, and administrative measures to protect personal data within our organization. Unfortunately, no transmission or storage system can be guaranteed to be completely secure, and transmission of information via the internet is not completely secure. If you have reason to believe that your interaction with us is no longer secure (for example, if you feel that the security of any account you might have with us has been compromised), please immediately <a href="<?= base_url('contact') ?>">notify us</a> of the problem.</p></section>

        <section id="retention"><span class="legal-section-number">11</span><h2>Retention</h2><p>We will only retain your personal data as long as reasonably required for you to use the Website, until you close your account or cancel your subscription, unless a longer retention period is required or permitted by law (for example, for regulatory purposes).</p></section>

        <section id="children"><span class="legal-section-number">12</span><h2>Our Policy on Children</h2><p>Our Website is not directed to children under 16. If a parent or guardian becomes aware that his or her child has provided us with information without their consent, he or she should contact us. We will delete such information from our files as soon as reasonably practicable.</p></section>

        <section id="your-rights"><span class="legal-section-number">13</span><h2>Your Rights</h2><ul><li><strong>Opt-out.</strong> You may contact us anytime to opt out of: (i) direct marketing communications; (ii) automated decision-making and/or profiling; (iii) our collection of sensitive personal data; (iv) any new processing of your personal data that we may carry out beyond the original purpose; or (v) the transfer of your personal data outside the EEA. Please note that your use of some of the Website may be ineffective upon opt-out.</li><li><strong>Access.</strong> You may access the information we hold about you at any time via your profile/account or by contacting us directly.</li><li><strong>Amend.</strong> You can also contact us to update or correct any inaccuracies in your personal data.</li><li><strong>Move.</strong> Your personal data is portable &mdash; you have the flexibility to move your data to other service providers as you wish.</li><li><strong>Erase and forget.</strong> In certain situations, for example when the information we hold about you is no longer relevant or is incorrect, you can request that we erase your data.</li></ul><p>If you wish to exercise any of these rights, please contact us. In your request, please make clear: (i) <strong>what</strong> personal data is concerned; and (ii) <strong>which of the above rights</strong> you would like to enforce. For your protection, we may only implement requests with respect to the personal data associated with the particular email address that you use to send us your request, and we may need to verify your identity before implementing your request. We will try to comply with your request as soon as reasonably practicable and, in any event, within one month of your request. Please note that we may need to retain certain information for recordkeeping purposes and/or to complete any transactions that you began prior to requesting such change or deletion.</p></section>

        <section id="complaints"><span class="legal-section-number">14</span><h2>Complaints</h2><p>We are committed to resolving any complaints about our collection or use of your personal data. If you would like to make a complaint regarding this Policy or our practices in relation to your personal data, please contact us through the information listed on our Website. We will reply to your complaint as soon as we can and, in any event, within 30 days. We hope to resolve any complaint brought to our attention. However, if you feel that your complaint has not been adequately resolved, you reserve the right to contact your local data protection supervisory authority.</p></section>

        <section id="contact-information"><span class="legal-section-number">15</span><h2>Contact Information</h2><p>We welcome your comments or questions about this Policy. You may <a href="<?= base_url('contact') ?>">contact us</a> in writing or through our Website.</p><div class="legal-contact-card"><div><span>Telephone</span><a href="tel:+<?= h(COMPANY_PHONE_TEL) ?>"><?= h(COMPANY_PHONE) ?></a></div><div><span>Fax</span><span><?= h(COMPANY_FAX) ?></span></div><div><span>Email</span><a href="mailto:<?= h(COMPANY_EMAIL) ?>"><?= h(COMPANY_EMAIL) ?></a></div><div><span>Mailing address</span><p><?= h(COMPANY_ADDRESS_LINE1) ?><br><?= h(COMPANY_ADDRESS_LINE2) ?></p></div></div></section>
      </article>
    </div>
  </section>
</main>

<?php require SITE_ROOT . '/common-template/footer.php'; ?>
