<?php
/** Terms of Service. Content supplied from the legacy LT Transfers website. */
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle       = 'Terms of Service | ' . SITE_NAME;
$pageDescription = 'Terms and conditions governing use of the LT Transfers website and services.';
$canonicalPath   = '/terms-of-service';
$bodyClass       = 'page-legal page-terms';

require SITE_ROOT . '/common-template/header.php';
?>

<main class="legal-main">
  <section class="page-hero legal-hero">
    <div class="breadcrumbs"><a href="<?= base_url('index.php') ?>">Home</a><span aria-hidden="true">/</span><span>Terms of Service</span></div>
    <div class="legal-hero-grid">
      <div><p class="eyebrow">Website terms</p><h1>Terms of Service</h1><p class="lede">The terms and conditions governing your use of the <?= h(SITE_NAME) ?> website and its available services.</p></div>
      <aside><span>Last updated</span><strong>December 1, 2020</strong><p>Please read these terms carefully before using this website.</p></aside>
    </div>
  </section>

  <section class="section legal-section">
    <div class="legal-layout">
      <aside class="legal-sidebar">
        <p class="eyebrow">On this page</p>
        <nav aria-label="Terms of Service sections">
          <a href="#introduction">Introduction</a><a href="#privacy-policy">Privacy Policy</a><a href="#your-account">Your Account</a><a href="#services">Services</a><a href="#third-party-services">Third Party Services</a><a href="#prohibited-uses">Prohibited Uses</a><a href="#company-materials">Company Materials</a><a href="#liabilities">Liabilities</a><a href="#indemnification">Indemnification</a><a href="#termination">Termination</a><a href="#miscellaneous">Miscellaneous</a><a href="#complaints">Complaints</a><a href="#contact-information">Contact Information</a>
        </nav>
        <div class="legal-help"><strong>Questions about these terms?</strong><a href="<?= base_url('contact') ?>">Contact our team <span aria-hidden="true">&rarr;</span></a></div>
      </aside>

      <article class="legal-content">
        <section id="introduction"><span class="legal-section-number">01</span><h2>Introduction</h2><p>The Terms and Conditions (&ldquo;<strong>Terms</strong>&rdquo;) describe how <strong>LT Transfers in Georgia (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; and &ldquo;our&rdquo;)</strong> regulates your use of this website, https://www.lttransfers.com (the &ldquo;<strong>Website</strong>&rdquo;). Please read the following information carefully to understand our practices regarding your use of the Website. The Company may change the Terms at any time. The Company may inform you of changes to the Terms using the available means of communication. The Company recommends that you check the Website frequently to see the current version of the Terms and any previous versions.</p><p>If you represent a legal entity, you certify that you are entitled by such legal entity to conclude the Terms as the legal entity you represent.</p></section>

        <section id="privacy-policy"><span class="legal-section-number">02</span><h2>Privacy Policy</h2><p>Our <a href="<?= base_url('privacy-policy') ?>">Privacy Policy</a> is available on a separate page. Our Privacy Policy explains how we process information about you. You shall understand that through your use of the Website you acknowledge that the processing of this information shall be undertaken in accordance with the Privacy Policy.</p></section>

        <section id="your-account"><span class="legal-section-number">03</span><h2>Your Account</h2><p>When using the Website, you shall be responsible for ensuring the confidentiality of your account, password, and other credentials and for secure access to your device. You shall not assign your account to anyone. The Company is not responsible for unauthorized access to your account that results from misappropriation or theft of your account. The Company may refuse or cancel service, terminate your account, and remove or edit content.</p><p>The Company does not knowingly collect personal data from persons under the age of 16 (sixteen). If you are under 16 (sixteen) years old, you may not use the Website and may not enter into the Terms under any circumstances.</p></section>

        <section id="services"><span class="legal-section-number">04</span><h2>Services</h2><p>The Website allows you to use services available on the Website. You shall not use the services for illegal aims.</p><p>We may, at our sole discretion, set fees for using the Website for you. All prices are published separately on relevant pages on the Website. We may, at our sole discretion, change any fees at any time.</p><p>We may use certified payment systems, which may also have commissions. Such commissions may be imposed on you when you choose a particular payment system. Detailed information about commissions of such payment systems may be found on their websites.</p></section>

        <section id="third-party-services"><span class="legal-section-number">05</span><h2>Third Party Services</h2><p>The Website may include links to other websites, applications, and platforms (hereinafter the &ldquo;<strong>Linked Sites</strong>&rdquo;).</p><p>The Company does not control the Linked Sites and shall not be responsible for their content or other materials. The Company makes these links available to you for providing functionality or services on the Website.</p></section>

        <section id="prohibited-uses"><span class="legal-section-number">06</span><h2>Prohibited Uses and Intellectual Property</h2><p>The Company grants you a non-transferable, non-exclusive, revocable license to access and use the Website from one device in accordance with the Terms. You shall not use the Website for any unlawful or prohibited purpose. You may not use the Website in a way that may disable, damage, or interfere with the Website.</p><p>All content present on the Website includes text, code, graphics, logos, images, compilation, and software used on the Website (hereinafter and hereinbefore the &ldquo;<strong>Content</strong>&rdquo;). The Content is the property of the Company or its contractors and is protected by intellectual property laws. You agree to observe all copyright and other proprietary notices or restrictions contained in the Content, and you are prohibited from changing the Content.</p><p>You may not publish, transmit, modify, reverse engineer, participate in the transfer of, or create and sell derivative works from any of the Content. Your enjoyment of the Website shall not entitle you to make any illegal or disallowed use of the Content. In particular, you shall not change proprietary rights or notices. You shall use the Content only for your personal and non-commercial use. The Company does not grant you any licenses to its intellectual property.</p></section>

        <section id="company-materials"><span class="legal-section-number">07</span><h2>The Company Materials</h2><p>By posting, uploading, inputting, providing, or submitting your Content, you grant the Company the right to use your Content in connection with the operation of the Company&rsquo;s business, including, but not limited to, the rights to transmit, publicly display, distribute, publicly perform, copy, reproduce, and translate your Content, and to publish your name in connection with your Content.</p><p>No compensation shall be paid with regard to the use of your Content. The Company shall have no obligation to publish or enjoy any Content you may send us and may remove your Content at any time.</p><p>By posting, uploading, inputting, providing, or submitting your Content, you warrant and represent that you own all of the rights to your Content.</p></section>

        <section id="liabilities"><span class="legal-section-number">08</span><h2>Disclaimer of Certain Liabilities</h2><p>The information available via the Website may include typographical errors or inaccuracies. The Company shall not be liable for these inaccuracies and errors.</p><p>The Company makes no representations about the availability, accuracy, reliability, suitability, and timeliness of the Content contained on and services available on the Website. To the maximum extent allowed by applicable law, all such Content and services are provided on an &ldquo;as is&rdquo; basis. The Company disclaims all warranties and conditions regarding this Content and services, including warranties and provisions of merchantability and fitness for a particular purpose.</p><p>To the maximum extent permitted by applicable law, in no event shall the Company be liable for any direct, indirect, incidental, consequential, special, or punitive damages, including, but not limited to, damages for loss of enjoyment, data, or profits, in connection with the enjoyment or execution of the Website, the inability or delay to enjoy the Website or its services, any Content of the Website, or otherwise arising out of the enjoyment of the Website, based on contract, non-contract liability, or other reason.</p><p>If the exclusion or limitation of liability for damages, whether consequential or incidental, is prohibited in a particular case, the exclusion or limitation of liability shall not apply to you.</p></section>

        <section id="indemnification"><span class="legal-section-number">09</span><h2>Indemnification</h2><p>You agree to indemnify, defend, and hold harmless the Company, its managers, directors, employees, agents, and third parties for any costs, losses, expenses (including attorneys&rsquo; fees), and liabilities regarding or arising out of your enjoyment of or inability to enjoy the Website or its services and the Company&rsquo;s services and products, your violation of the Terms, your violation of any rights of third parties, or your violation of applicable law. The Company may assume the exclusive defense, and you shall cooperate with the Company in asserting any available defenses.</p></section>

        <section id="termination"><span class="legal-section-number">10</span><h2>Termination and Access Restriction</h2><p>The Company may terminate your access and account to the Website and its related services, or any part thereof, at any time without notice in the event of your violation of the Terms.</p></section>

        <section id="miscellaneous"><span class="legal-section-number">11</span><h2>Miscellaneous</h2><p>The governing law of the Terms shall be the substantive laws of the country where the Company is established, except for conflict-of-law rules. You shall not use the Website in jurisdictions that do not give effect to all provisions of the Terms.</p><p>No joint venture, partnership, employment, or agency relationship shall be implied between you and the Company as a result of the Terms or use of the Website.</p><p>Nothing in the Terms shall derogate from the Company&rsquo;s right to comply with governmental, court, police, and law enforcement requests or requirements regarding your enjoyment of the Website.</p><p>If any part of the Terms is determined to be void or unenforceable in accordance with applicable law, the void or unenforceable clauses will be deemed superseded by valid and enforceable clauses similar to the original version of the Terms, and the other parts and sections of the Terms shall remain applicable to you and the Company.</p><p>The Terms constitute the entire agreement between you and the Company regarding the enjoyment of the Website and supersede all prior communications and offers, whether electronic, oral, or written, between you and the Company.</p><p>The Company and its affiliates shall not be liable for a failure or delay to fulfill their obligations where the failure or delay results from any cause beyond the Company&rsquo;s reasonable control, including technical failures, natural disasters, blockages, embargoes, riots, acts, regulations, legislation, or orders of government, terrorist acts, war, or any other force outside the Company&rsquo;s control.</p><p>In case of controversies, demands, claims, disputes, or causes of action between the Company and you relating to the Website, related issues, or the Terms, you and the Company agree to attempt to resolve such matters through good-faith negotiation and, if such negotiation fails, exclusively through the courts of the country where the Company is established.</p></section>

        <section id="complaints"><span class="legal-section-number">12</span><h2>Complaints</h2><p>We are committed to resolving complaints about our collection or use of your personal data. If you would like to make a complaint regarding these Terms or our practices in relation to your personal data, please contact us through our Website. We will reply to your complaint as soon as we can and, in any event, within 30 days. We hope to resolve any complaint brought to our attention. However, if you feel that your complaint has not been adequately resolved, you reserve the right to contact your local data protection supervisory authority.</p></section>

        <section id="contact-information"><span class="legal-section-number">13</span><h2>Contact Information</h2><p>We welcome your comments or questions about our Terms. You may <a href="<?= base_url('contact') ?>">contact us</a> through the contact information available on our Website.</p><div class="legal-contact-card"><div><span>Telephone</span><a href="tel:+<?= h(COMPANY_PHONE_TEL) ?>"><?= h(COMPANY_PHONE) ?></a></div><div><span>Email</span><a href="mailto:<?= h(COMPANY_EMAIL) ?>"><?= h(COMPANY_EMAIL) ?></a></div><div><span>Mailing address</span><p><?= h(COMPANY_ADDRESS_LINE1) ?><br><?= h(COMPANY_ADDRESS_LINE2) ?></p></div></div></section>
      </article>
    </div>
  </section>
</main>

<?php require SITE_ROOT . '/common-template/footer.php'; ?>
